select * from LOG_REGISTRO_LINK_PAGOS;

SELECT * FROM PARAMETRIZACION WHERE NOMBRE in ('COD_RECAUDO_PADRE', 'COD_RECAUDO_HIJO');

SELECT J.DIGITO_CHEQUEO, J.*
FROM JURIDICOS J
WHERE NUMERO_DOCUMENTO IN ('860002180','860035977');

select P.COD_TRANSACCION_SB,P.F_TRANSACCION_SB, p.*
from botonpse.parametros_pse P
WHERE F_TRANSACCION_SB+(30/1440) < SYSDATE