| NOMBRE DEL CAMPO | TABLA ORIGEN | CAMPO ORIGEN | PROCEDIMIENTO/FUNCIÓN | OBSERVACIONES |
|-----------------|--------------|--------------|------------------------|---------------|
| SOLICITUD | SLCTDES_ESTDIOS | SES_NMRO | PRC_CONSULTA_SOLICITUD, PRC_CONSULTA_RESULTADOS, PRC_CONSULTA_SOLICITUDES | Campo principal de identificación |
| POLIZA | SLCTDES_ESTDIOS | SES_NMRO_PLZA | PRC_CONSULTA_SOLICITUDES | También puede venir de AEW_ESTUDIOS.COD_INMOBILIARIA |
| SUCURSAL_POLIZA | SLCTDES_ESTDIOS | SES_SUC_CDGO | PRC_CONSULTA_SOLICITUD | Sucursal de la solicitud |
| TIPO_POLIZA | PLZAS | POL_TPOPLZA | (Requiere JOIN con PLZAS) | No está directamente en el paquete, requiere consulta adicional |
| ESTADO_POLIZA | PLZAS | POL_ESTADO_PLZA | (Requiere JOIN con PLZAS) | No está directamente en el paquete, requiere consulta adicional |
| TID_TOMADOR | PLZAS | POL_PRS_TPO_IDNTFCCION | (Requiere JOIN con PLZAS) | Tipo identificación tomador de póliza |
| TOMADOR | PLZAS | POL_PRS_NMRO_IDNTFCCION | (Requiere JOIN con PLZAS) | Número identificación tomador |
| KEY_ID_TOMADOR | PLZAS | POL_PRS_NMRO_IDNTFCCION \|\| POL_PRS_TPO_IDNTFCCION | (Requiere JOIN con PLZAS) | Concatenación de identificación |
| POLIZA_FAC_MENSUAL | PLZAS | POL_FCTRA_MNSUAL | (Requiere JOIN con PLZAS) | Facturación mensual |
| POLIZA_VIP | PLZAS | POL_CLNTE_VIP | (Requiere JOIN con PLZAS) | Cliente VIP |
| FECHA_RADICA | SLCTDES_ESTDIOS | SES_FCHA_INGRSO | PRC_CONSULTA_SOLICITUD, PRC_CONSULTA_SOLICITUDES | Fecha de ingreso/radicación. También AEW_ESTUDIOS.FEC_DILIGENCIA |
| TIPO_SOLICITUD | SLCTDES_ESTDIOS | SES_TPO_SLCTUD | PRC_CONSULTA_SOLICITUD, FUN_TIPO_SOLICITUD | Tipo de solicitud |
| ESTUDIO_AGRUPADO | SLCTDES_ESTDIOS | SES_NMRO_ESTDIOS_RLZDOS | PRC_CONSULTA_SOLICITUD | Número de estudios realizados |
| TIPO_INMUEBLE | SLCTDES_ESTDIOS | SES_TPO_INMBLE | PRC_CONSULTA_SOLICITUD | Tipo de inmueble (código) |
| DESTINO_INMUEBLE | SLCTDES_ESTDIOS | SES_DSTNO_INMBLE | PRC_CONSULTA_SOLICITUD, PRC_CONSULTA_SOLICITUDES | Destino del inmueble (código). Descripción en CG_REF_CODES |
| VALOR_CANON | SLCTDES_ESTDIOS | SES_CNON_ARRNDMNTO | PRC_CONSULTA_SOLICITUD, PRC_CONSULTA_SOLICITUDES | Valor del canon de arrendamiento. También AEW_ESTUDIOS.VLR_CANON |
| VALOR_ADMON | SLCTDES_ESTDIOS | SES_CTA_ADMNSTRCION | PRC_CONSULTA_SOLICITUD, PRC_CONSULTA_SOLICITUDES | Valor administración. También AEW_ESTUDIOS.VLR_ADMIN |
| ID_ANALISTA | SLCTDES_ESTDIOS | SES_CDGO_ANLSTA | PRC_CONSULTA_SOLICITUD | Código del analista |
| TID_ANALISTA | RSLTDOS_ARRNDTRIOS | REA_CDGO_ANLSTA | PRC_CONSULTA_RESULTADOS | Tipo identificación analista (requiere validación) |
| ANALISTA | RSLTDOS_ARRNDTRIOS | REA_CDGO_ANLSTA | PRC_CONSULTA_RESULTADOS | Código analista que procesó resultado |
| VALOR_ESTUDIO | SLCTDES_ESTDIOS | SES_VLR_ESTDIO | PRC_CONSULTA_SOLICITUD | Valor del estudio. También AEW_ESTUDIOS.VALOR_ESTUDIO |
| DESCUENTO | SLCTDES_ESTDIOS | SES_VLOR_DESCTO | PRC_CONSULTA_SOLICITUD | Valor del descuento |
| VALOR_RECAUDADO | SLCTDES_ESTDIOS | SES_PGO_PGDO | PRC_CONSULTA_SOLICITUD | Pago pagado/valor recaudado |
| ESTUDIO_CON_DEUDA | SLCTDES_ESTDIOS | SES_DEUDA | PRC_CONSULTA_SOLICITUD | Información de deuda |
| ES_UAR | SLCTDES_ESTDIOS | SES_UAR | PRC_CONSULTA_SOLICITUD | Indicador UAR |
| MEDIO_RADICADION | SLCTDES_ESTDIOS | SES_SISTEMA_ORIGEN | PRC_CONSULTA_SOLICITUD | Sistema origen (S=SAI, otros valores) |
| NATURALEZA_INQUILINO | ARRNDTRIOS | ARR_TPO_ARRNDTRIO | PRC_CONSULTA_ARRNDTRIOS, PRC_CONSULTA_RESULTADOS | Tipo arrendatario: P=Principal, I=Inquilino, S=Solidario |
| DIRECCION | DIRECCIONES | DI_DIRECCION | PRC_CONSULTA_DIRECCION, PRC_CONSULTA_SOLICITUD, PRC_CONSULTA_SOLICITUDES | Dirección del inmueble (tipo 'E') |
| CIUDAD_DIRECCION | V_DIVISION_POLITICAS | NOM_CIU | PRC_CONSULTA_DIRECCION, PRC_CONSULTA_SOLICITUD, PRC_CONSULTA_SOLICITUDES | Nombre ciudad desde DIVISION_POLITICAS |
| ID_ULTIMO_ANA_ENCARGADO | RSLTDOS_ARRNDTRIOS | REA_CDGO_ANLSTA | PRC_CONSULTA_RESULTADOS | Analista del último resultado (MAX fecha) |
| ULTIMO_ANA_ENCARGADO | RSLTDOS_ARRNDTRIOS | REA_CDGO_ANLSTA | PRC_CONSULTA_RESULTADOS | Código analista último resultado |
| ULTIMA_FEC_MOVIMIENTO | RSLTDO_ESTDIO | RET_FCHA_RSLTDO | PRC_CONSULTA_RESULTADOS, PRC_CONSULTA_SOLICITUDES | Fecha último resultado. También RSLTDOS_ARRNDTRIOS.REA_FCHA_RSLTDO |
| TID_EJECUTIVO_POL | PLZAS | POL_PRS_TPO_IDNTFCCION | (Requiere JOIN con PLZAS) | Tipo identificación ejecutivo póliza |
| ID_EJECUTIVO_POL | PLZAS | POL_PRS_NMRO_IDNTFCCION | (Requiere JOIN con PLZAS) | Identificación ejecutivo póliza |
| EJECUTIVO | PLZAS | POL_PRS_NMRO_IDNTFCCION | (Requiere JOIN con PLZAS) | Nombre ejecutivo (requiere PK_TERCEROS.F_NOMBRES) |
| F_INGRESO_SEGURO | PLZAS | POL_FCHA_DSDE_INCIAL | (Requiere JOIN con PLZAS) | Fecha inicio vigencia póliza |
| F_RETIRO_SEGURO | PLZAS | POL_FCHA_HSTA_ACTUAL | (Requiere JOIN con PLZAS) | Fecha fin vigencia póliza |
| FEC_PRIMER_RESULTADO | RSLTDO_ESTDIO | MIN(RET_FCHA_RSLTDO) | (Requiere consulta agregada) | Primera fecha de resultado |
| PRIMER_ESTUDIO | RSLTDO_ESTDIO | MIN(RET_NMRO_SLCTUD) | (Requiere consulta agregada) | Primera solicitud con resultado |
| PRIMER_RESULTADO | RSLTDO_ESTDIO | RET_CDGO_RSLTDO WHERE MIN(RET_FCHA_RSLTDO) | (Requiere consulta agregada) | Código primer resultado |
| PRIMER_USER_REGISTRO | RSLTDO_ESTDIO | RET_USRIO WHERE MIN(RET_FCHA_RSLTDO) | (Requiere consulta agregada) | Usuario primer registro |
| USUARIO_PRIMER_REGISTRO | RSLTDO_ESTDIO | RET_USRIO WHERE MIN(RET_FCHA_RSLTDO) | (Requiere consulta agregada) | Usuario primer registro |
| FEC_ULTIMO_RESULTADO | RSLTDO_ESTDIO | MAX(RET_FCHA_RSLTDO) | PRC_CONSULTA_RESULTADOS | Última fecha resultado. También SLCTDES_ESTDIOS.SES_FCHA_ULTMO_RSLTDO |
| ULTIMO_ESTUDIO | RSLTDO_ESTDIO | RET_NMRO_SLCTUD WHERE MAX(RET_FCHA_RSLTDO) | PRC_CONSULTA_RESULTADOS | Última solicitud con resultado |
| ULTIMO_RESULTADO | RSLTDO_ESTDIO | RET_CDGO_RSLTDO WHERE MAX(RET_FCHA_RSLTDO) | PRC_CONSULTA_RESULTADOS | Código último resultado |
| ULTIMO_USER_REGISTRO | RSLTDO_ESTDIO | RET_USRIO WHERE MAX(RET_FCHA_RSLTDO) | PRC_CONSULTA_RESULTADOS | Usuario último registro |
| USUARIO_ULTIMO_REGISTRO | RSLTDO_ESTDIO | RET_USRIO WHERE MAX(RET_FCHA_RSLTDO) | PRC_CONSULTA_RESULTADOS | Usuario último registro |
| CODIGO_RESULTADO_FINAL | RSLTDO_ESTDIO | RET_CDGO_RSLTDO | PRC_CONSULTA_RESULTADOS, PRC_CONSULTA_SOLICITUDES | Código resultado final. También AEW_RESULTADOS_ESTUDIO.COD_SECUNDARIO |
| MARCA_GESTION_DIRECTA | SLCTDES_ESTDIOS | SES_ESTRATEGIA | PRC_CONSULTA_SOLICITUD | Estrategia de gestión |
| TIPO_DOCUMENTO_EVALUADO | ARRNDTRIOS | ARR_TPO_IDNTFCCION | PRC_CONSULTA_ARRNDTRIOS, PRC_CONSULTA_RESULTADOS | Tipo documento arrendatario evaluado |
| KEY_ID_EVALUADO | ARRNDTRIOS | ARR_NMRO_IDNTFCCION \|\| ARR_TPO_IDNTFCCION | PRC_CONSULTA_ARRNDTRIOS | Concatenación identificación evaluado |
| TIPO_ROL | ARRNDTRIOS | ARR_TPO_ARRNDTRIO | PRC_CONSULTA_ARRNDTRIOS, PRC_CONSULTA_RESULTADOS | Tipo rol: P=Principal, I=Inquilino, S=Solidario |
| INGRESOS | AEW_DEUDORES | INGRESOS | PRC_CONSULTA_RESULTADOS, PRC_CONSULTA_SOLICITUDES | Ingresos del deudor |
| DUPLICADO | (No encontrado) | - | - | Requiere validación adicional |
| FECHA_DILIGENCIA | AEW_ESTUDIOS | FEC_DILIGENCIA | PRC_CONSULTA_SOLICITUDES | Fecha diligencia en análisis digital |
| FECHA_SOLICITUD_MES | SLCTDES_ESTDIOS | TO_CHAR(SES_FCHA_INGRSO,'MM') | (Requiere función) | Mes de radicación |
| FECHA_SOLICITUD_DIA | SLCTDES_ESTDIOS | TO_CHAR(SES_FCHA_INGRSO,'DD') | (Requiere función) | Día de radicación |
| nombreInquilino | ARRNDTRIOS | PK_TERCEROS.F_NOMBRES(ARR_NMRO_IDNTFCCION, ARR_TPO_IDNTFCCION) | PRC_CONSULTA_ARRNDTRIOS, PRC_CONSULTA_RESULTADOS, PRC_CONSULTA_SOLICITUDES | Nombre completo del inquilino |
| correoInquilino | AEW_DEUDORES | CORREO | PRC_CONSULTA_SOLICITUDES | Correo del inquilino. También PK_TERCEROS.FUN_RET_MEDIO_TERCERO |
| telefonoInquilino | AEW_DEUDORES | NUM_TELEFONO | PRC_CONSULTA_SOLICITUDES | Teléfono del inquilino. También PK_TERCEROS.FUN_RET_MEDIO_TERCERO |
| fechaExpedicion | AEW_DEUDORES | FECHA_EXPEDICION | PRC_CONSULTA_RESULTADOS, PRC_CONSULTA_SOLICITUDES | Fecha expedición documento |
| nombreAsesor | AEW_ESTUDIOS | NOMBRE_ASESOR | PRC_CONSULTA_SOLICITUDES | Nombre del asesor |
| correoAsesor | AEW_ESTUDIOS | CORREO_ASESOR | PRC_CONSULTA_SOLICITUDES | Correo del asesor |
| descripcionResultado | RSLTDO_ESTDIO | RET_OBSRVCION | PRC_CONSULTA_RESULTADOS, PRC_CONSULTA_DESTINO | Descripción/observación del resultado |
| codigoResultado | RSLTDO_ESTDIO | RET_CDGO_RSLTDO | PRC_CONSULTA_RESULTADOS, PRC_CONSULTA_SOLICITUDES | Código del resultado |
| tipoDeudor | ARRNDTRIOS | DECODE(ARR_TPO_ARRNDTRIO,'I','INQUILINO','P','INQUILINO','DEUDOR SOLIDARIO') | PRC_CONSULTA_RESULTADOS | Tipo de deudor formateado |
