select * from LOG_REGISTRO_LINK_PAGOS;
;-- -. . -..- - / . -. - .-. -.--
SELECT *
INTO REG_SOLICITUD
FROM OBLIGACIONES_PAGAR A
WHERE A.ESTADO_SOLICITUD = 'V'
  AND A.ESTADO_PAGO = 'PE'
  AND TRUNC(FECHA_LIMITE_PAGO) >= TRUNC(SYSDATE);
;-- -. . -..- - / . -. - .-. -.--
SELECT A.*
INTO REG_SOLICITUD
FROM OBLIGACIONES_PAGAR A
WHERE A.ESTADO_SOLICITUD = 'V'
  AND A.ESTADO_PAGO = 'PE'
  AND TRUNC(FECHA_LIMITE_PAGO) >= TRUNC(SYSDATE);
;-- -. . -..- - / . -. - .-. -.--
SELECT A.*
INTO REG_SOLICITUD
FROM OBLIGACIONES_PAGAR A
WHERE A.ESTADO_SOLICITUD = 'V'
  AND A.ESTADO_PAGO = 'PE'
  AND TRUNC(A.FECHA_LIMITE_PAGO) >= TRUNC(SYSDATE);
;-- -. . -..- - / . -. - .-. -.--
SELECT A.*
FROM OBLIGACIONES_PAGAR A
WHERE A.ESTADO_SOLICITUD = 'V'
  AND A.ESTADO_PAGO = 'PE'
  AND TRUNC(A.FECHA_LIMITE_PAGO) >= TRUNC(SYSDATE);
;-- -. . -..- - / . -. - .-. -.--
SELECT A.*
FROM OBLIGACIONES_PAGAR A
WHERE A.ESTADO_SOLICITUD = 'V'
  AND A.ESTADO_PAGO = 'PE';
;-- -. . -..- - / . -. - .-. -.--
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'OBLIGACIONES_PAGAR';
;-- -. . -..- - / . -. - .-. -.--
SELECT VALOR INTO valor FROM PARAMETRIZACION WHERE NOMBRE in ('COD_RECAUDO_PADRE', 'COD_RECAUDO_HIJO');
;-- -. . -..- - / . -. - .-. -.--
SELECT VALOR FROM PARAMETRIZACION WHERE NOMBRE in ('COD_RECAUDO_PADRE', 'COD_RECAUDO_HIJO');
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM PARAMETRIZACION WHERE NOMBRE in ('COD_RECAUDO_PADRE', 'COD_RECAUDO_HIJO');
;-- -. . -..- - / . -. - .-. -.--
SELECT J.DIGITO_CHEQUEO, J.*
FROM JURIDICOS J
WHERE NUMERO_DOCUMENTO IN ('860002180','860035977');
;-- -. . -..- - / . -. - .-. -.--
select P.COD_TRANSACCION_SB,P.F_TRANSACCION_SB
from botonpse.parametros_pse P
WHERE F_TRANSACCION_SB+(30/1440) < SYSDATE;
;-- -. . -..- - / . -. - .-. -.--
select P.COD_TRANSACCION_SB,P.F_TRANSACCION_SB, p.*
from botonpse.parametros_pse P
WHERE F_TRANSACCION_SB+(30/1440) < SYSDATE;