SELECT * from A2000030 WHERE NUM_POL1 = 1530375077401


SELECT R1.NUM_SECU_EXPED
FROM   A7001200 R1,
       (SELECT R.NUM_SECU_EXPED, SUM(VALOR_ACTUAL) VALOR_ACTUAL
        FROM A7001200 R,
             (SELECT DISTINCT E.NUM_SECU_EXPED NUM_SECU_EXPED
              FROM   A7001000 E
              WHERE  E.COD_CIA = 3
                AND    E.COD_SECC = 1
                AND    (E.FEC_APER_EXP = TRUNC(SYSDATE)
                  OR     E.FEC_MODI_EXP = TRUNC(SYSDATE))) X
        WHERE  X.NUM_SECU_EXPED = R.NUM_SECU_EXPED
        GROUP BY R.NUM_SECU_EXPED) Y
WHERE  Y.NUM_SECU_EXPED = R1.NUM_SECU_EXPED
  AND    R1.NRO_ORDEN_EXP = (SELECT MAX(R2.NRO_ORDEN_EXP)
                             FROM A7001200 R2
                             WHERE R2.NUM_SECU_EXPED = R1.NUM_SECU_EXPED)
  AND    R1.VALOR_ACTUAL <> Y.VALOR_ACTUAL;


SELECT R1.NUM_SECU_EXPED
FROM A7001200 R1,
     (SELECT R.NUM_SECU_EXPED, SUM(VALOR_ACTUAL) VALOR_ACTUAL
      FROM A7001200 R,
           (SELECT DISTINCT E.NUM_SECU_EXPED NUM_SECU_EXPED
            FROM A7001000 E
            WHERE E.COD_CIA = 3
              AND E.COD_SECC = 1
              AND (E.FEC_APER_EXP = TRUNC(date '2021-05-25')
                OR E.FEC_MODI_EXP = TRUNC(date '2021-05-25'))) X
      WHERE X.NUM_SECU_EXPED = R.NUM_SECU_EXPED
      GROUP BY R.NUM_SECU_EXPED) Y
WHERE Y.NUM_SECU_EXPED = R1.NUM_SECU_EXPED
  AND R1.NRO_ORDEN_EXP = (SELECT MAX(R2.NRO_ORDEN_EXP)
                          FROM A7001200 R2
                          WHERE R2.NUM_SECU_EXPED = R1.NUM_SECU_EXPED)
  AND R1.VALOR_ACTUAL <> Y.VALOR_ACTUAL;