---procedure PROVISION_PRIMAS
SELECT ALL PLZAS.POL_SUC_CIA_CDGO COD_CIA,
           SCRSL.SUC_CDGO SUCURSAL,
           PLZAS.POL_NMRO_PLZA Poliza,
           PLZAS.POL_PRS_TPO_IDNTFCCION TIPO_IDEN,
           PLZAS.POL_PRS_NMRO_IDNTFCCION Identificacion,
           INITCAP(PK_TERCEROS.F_NOMBRES(PLZAS.POL_PRS_NMRO_IDNTFCCION,
                                         PLZAS.POL_PRS_TPO_IDNTFCCION)) NombrePoliza,
           PLZAS.POL_TPOPLZA TIPO_POLIZA,
           CRTFCDOS.CER_NMRO_CRTFCDO NumCert,
           CRTFCDOS.CER_CLSE_PLZA CLASE,
           CRTFCDOS.CER_RAM_CDGO RAMO,
           CRTFCDOS.CER_FCHA_DSDE_ACTUAL FECHA_CER,
           (SUM(NVL(CRTFCDOS.CER_VLOR_PRMA_TTAL, 0)) / COUNT(9)) -
           (SUM(DECODE(ESTADO_CTA_RCBOS.EST_CDGO_CNCPTO,'PRM',
                       ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO,'GSE',
                       ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO,'IVA',
                       ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO,0))) Prima
FROM PLZAS, CRTFCDOS, SCRSL, ESTADO_CTA_RCBOS, CRTFCDO_ANLDO
WHERE CRTFCDOS.CER_VLOR_SLDO > 2
  AND CRTFCDOS.CER_NMRO_PLZA = 1143
  AND CRTFCDOS.CER_FCHA_PRDCCION >= to_date('01/10/2011', 'dd/mm/yyyy')
  AND CRTFCDOS.CER_ESTDO_PRDCCION NOT IN ('00','70','80')
  AND ESTADO_CTA_RCBOS.EST_ESTDO_RCBO(+) = 'I'
  AND ESTADO_CTA_RCBOS.EST_ORGEN_RCDO(+) = 'P'
  AND ESTADO_CTA_RCBOS.EST_FCHA_MRA(+) IS NULL
  AND ESTADO_CTA_RCBOS.EST_FCHA_MVTO(+) BETWEEN to_date('01/01/1900', 'dd/mm/yyyy') AND (to_date('30/04/2025', 'dd/mm/yyyy') + 1)
  --AND (SCRSL.SUC_CDGO = NVL('2501', SCRSL.SUC_CDGO))
  AND ((PLZAS.POL_SUC_CIA_CDGO = SCRSL.SUC_CIA_CDGO)
    AND (PLZAS.POL_SUC_CDGO = SCRSL.SUC_CDGO)
    AND (PLZAS.POL_TPOPLZA = 'C')
    AND (CRTFCDOS.CER_RAM_CDGO = PLZAS.POL_RAM_CDGO)
    AND (CRTFCDOS.CER_CLSE_PLZA = PLZAS.POL_CDGO_CLSE)
    AND (CRTFCDOS.CER_NMRO_PLZA = PLZAS.POL_NMRO_PLZA)
    AND (ESTADO_CTA_RCBOS.EST_SLCTUD(+) = CRTFCDOS.CER_NMRO_CRTFCDO)
    AND (ESTADO_CTA_RCBOS.EST_PLZA(+) = CRTFCDOS.CER_NMRO_PLZA)
    AND (CRTFCDO_ANLDO.CER_NMRO_CRTFCDO(+) = CRTFCDOS.CER_NMRO_CRTFCDO)
    AND (CRTFCDO_ANLDO.CER_NMRO_PLZA(+) = CRTFCDOS.CER_NMRO_PLZA)
    AND (CRTFCDO_ANLDO.CER_CLSE_PLZA(+) = CRTFCDOS.CER_CLSE_PLZA)
    AND (CRTFCDO_ANLDO.CER_RAM_CDGO(+) = CRTFCDOS.CER_RAM_CDGO))
GROUP BY PLZAS.POL_SUC_CIA_CDGO,
         SCRSL.SUC_CDGO,
         PLZAS.POL_NMRO_PLZA,
         PLZAS.POL_PRS_TPO_IDNTFCCION,
         PLZAS.POL_PRS_NMRO_IDNTFCCION,
         INITCAP(PK_TERCEROS.F_NOMBRES(PLZAS.POL_PRS_NMRO_IDNTFCCION,
                                       PLZAS.POL_PRS_TPO_IDNTFCCION)),
         PLZAS.POL_TPOPLZA,
         CRTFCDOS.CER_NMRO_CRTFCDO,
         CRTFCDOS.CER_CLSE_PLZA,
         CRTFCDOS.CER_RAM_CDGO,
         CRTFCDOS.CER_FCHA_DSDE_ACTUAL
HAVING(SUM(NVL(CRTFCDOS.CER_GSTOS_EXPDCION, 0) +
           CRTFCDOS.CER_VLOR_IVA +
           CRTFCDOS.CER_VLOR_PRMA_NTA +
           CRTFCDOS.CER_VLOR_PPLRIA +
           NVL(CRTFCDOS.CER_VLOR_CTA_FAX, 0) +
           NVL(CRTFCDOS.CER_VLOR_CTA_PRMA, 0)) / COUNT(9)) -
      (SUM(DECODE(ESTADO_CTA_RCBOS.EST_CDGO_CNCPTO, 'PRM',
                  ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'GSE',
                  ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'IVA',
                  ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CPL',
                  ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CFI',
                  ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CFX',
                  ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 0))) > 0
UNION
SELECT ALL PLZAS.POL_SUC_CIA_CDGO COD_CIA,
           SCRSL.SUC_CDGO SUCURSAL,
           PLZAS.POL_NMRO_PLZA Poliza,
           PLZAS.POL_PRS_TPO_IDNTFCCION TIPO_IDEN,
           PLZAS.POL_PRS_NMRO_IDNTFCCION Identificacion,
           INITCAP(PK_TERCEROS.F_NOMBRES(PLZAS.POL_PRS_NMRO_IDNTFCCION,
                                         PLZAS.POL_PRS_TPO_IDNTFCCION)) NombrePoliza,
           PLZAS.POL_TPOPLZA TIPO_POLIZA,
           CRTFCDOS.CER_NMRO_CRTFCDO NumCert,
           CRTFCDOS.CER_CLSE_PLZA CLASE,
           CRTFCDOS.CER_RAM_CDGO RAMO,
           CRTFCDOS.CER_FCHA_DSDE_ACTUAL FECHA_CER,
           (SUM(NVL(CRTFCDOS.CER_VLOR_PRMA_TTAL, 0) +
                NVL(CRTFCDOS.CER_GSTOS_EXPDCION, 0)) / COUNT(9)) -
           (SUM(DECODE(ESTADO_CTA_RCBOS.EST_CDGO_CNCPTO,'PRM',
                       ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO,'GSE',
                       ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO,'IVA',
                       ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO,0))) Prima
FROM PLZAS,
     CRTFCDOS,
     SCRSL,
     ESTADO_CTA_RCBOS,
     CRTFCDO_ANLDO,
     CG_REF_CODES
WHERE (CRTFCDOS.CER_VLOR_SLDO > 2
    AND CRTFCDOS.CER_NMRO_PLZA = 1143
    AND CRTFCDOS.CER_FCHA_PRDCCION >= to_date('01/10/2011', 'dd/mm/yyyy')
    AND CRTFCDOS.CER_ESTDO_PRDCCION NOT IN ('00','70','80')
    AND ESTADO_CTA_RCBOS.EST_ESTDO_RCBO(+) = 'I'
    AND ESTADO_CTA_RCBOS.EST_ORGEN_RCDO(+) = 'P'
    AND ESTADO_CTA_RCBOS.EST_FCHA_MRA(+) IS NULL
    AND ESTADO_CTA_RCBOS.EST_FCHA_MVTO(+) BETWEEN to_date('01/01/1900', 'dd/mm/yyyy')
           AND (to_date('30/04/2025', 'dd/mm/yyyy') + 1) AND CG_REF_CODES.RV_DOMAIN = 'ESTADO_POLIZA')
  AND ((CRTFCDOS.CER_NMRO_CRTFCDO, CRTFCDOS.CER_NMRO_PLZA) IN
       (SELECT A.EST_SLCTUD, A.EST_PLZA
        FROM ESTADO_CTA_RCBOS A
        WHERE A.EST_ESTDO_RCBO = 'I'
          AND A.EST_ORGEN_RCDO = 'P'
          AND A.EST_FCHA_MRA IS NULL
          AND A.EST_FCHA_MVTO > to_date('30/04/2025', 'dd/mm/yyyy')))
  --AND (SCRSL.SUC_CDGO = NVL('2501', SCRSL.SUC_CDGO))
  AND ((PLZAS.POL_SUC_CIA_CDGO = SCRSL.SUC_CIA_CDGO)
    AND (PLZAS.POL_SUC_CDGO = SCRSL.SUC_CDGO)
    AND (PLZAS.POL_TPOPLZA = 'C')
    AND (CRTFCDOS.CER_RAM_CDGO = PLZAS.POL_RAM_CDGO)
    AND (CRTFCDOS.CER_CLSE_PLZA = PLZAS.POL_CDGO_CLSE)
    AND (CRTFCDOS.CER_NMRO_PLZA = PLZAS.POL_NMRO_PLZA)
    AND (ESTADO_CTA_RCBOS.EST_SLCTUD(+) = CRTFCDOS.CER_NMRO_CRTFCDO)
    AND (ESTADO_CTA_RCBOS.EST_PLZA(+) = CRTFCDOS.CER_NMRO_PLZA)
    AND (CRTFCDO_ANLDO.CER_NMRO_CRTFCDO(+) = CRTFCDOS.CER_NMRO_CRTFCDO)
    AND (CRTFCDO_ANLDO.CER_NMRO_PLZA(+) = CRTFCDOS.CER_NMRO_PLZA)
    AND (CRTFCDO_ANLDO.CER_CLSE_PLZA(+) = CRTFCDOS.CER_CLSE_PLZA)
    AND (CRTFCDO_ANLDO.CER_RAM_CDGO(+) = CRTFCDOS.CER_RAM_CDGO)
    AND (CG_REF_CODES.RV_LOW_VALUE = PLZAS.POL_ESTADO_PLZA))
GROUP BY PLZAS.POL_SUC_CIA_CDGO,
         SCRSL.SUC_CDGO,
         PLZAS.POL_NMRO_PLZA,
         PLZAS.POL_PRS_TPO_IDNTFCCION,
         PLZAS.POL_PRS_NMRO_IDNTFCCION,
         INITCAP(PK_TERCEROS.F_NOMBRES(PLZAS.POL_PRS_NMRO_IDNTFCCION,
                                       PLZAS.POL_PRS_TPO_IDNTFCCION)),
         PLZAS.POL_TPOPLZA,
         CRTFCDOS.CER_NMRO_CRTFCDO,
         CRTFCDOS.CER_CLSE_PLZA,
         CRTFCDOS.CER_RAM_CDGO,
         CRTFCDOS.CER_FCHA_DSDE_ACTUAL
HAVING    (SUM(NVL(CRTFCDOS.CER_GSTOS_EXPDCION, 0) +
               CRTFCDOS.CER_VLOR_IVA +
               CRTFCDOS.CER_VLOR_PRMA_NTA +
               CRTFCDOS.CER_VLOR_PPLRIA +
               NVL(CRTFCDOS.CER_VLOR_CTA_FAX, 0) +
               NVL(CRTFCDOS.CER_VLOR_CTA_PRMA, 0)) / COUNT(9)) -
          (SUM(DECODE(ESTADO_CTA_RCBOS.EST_CDGO_CNCPTO, 'PRM',
                      ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'GSE',
                      ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'IVA',
                      ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CPL',
                      ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CFI',
                      ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CFX',
                      ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 0))) > 0
ORDER BY SUCURSAL, POLIZA;

SELECT CER_NMRO_PLZA, MIN(CER_FCHA_PRDCCION) FECHA, min(CER_FCHA_DSDE_ACTUAL)
FROM CRTFCDOS, PLZAS
WHERE CER_VLOR_SLDO > 2
  AND CER_FCHA_PRDCCION >= to_date('01/01/1900', 'dd/mm/yyyy')
  AND CER_FCHA_PRDCCION <= to_date('30/04/2025', 'dd/mm/yyyy')
  AND POL_TPOPLZA = 'C'
  AND CER_ESTDO_PRDCCION NOT IN ('00','70','80', '50')
  AND CER_RAM_CDGO = POL_RAM_CDGO
  AND CER_CLSE_PLZA = POL_CDGO_CLSE
  AND CER_NMRO_PLZA = POL_NMRO_PLZA
  AND CER_FCHA_PRDCCION < to_date('30/04/2025', 'dd/mm/yyyy') - 75
  AND CRTFCDOS.CER_NMRO_PLZA = 1143
GROUP BY CER_NMRO_PLZA
UNION
SELECT CER_NMRO_PLZA, MIN(CER_FCHA_PRDCCION) FECHA, min(CER_FCHA_DSDE_ACTUAL)
FROM PLZAS,CRTFCDOS
WHERE CER_VLOR_SLDO > 2
  AND CER_FCHA_PRDCCION >= to_date('01/01/1900', 'dd/mm/yyyy')
  AND CER_FCHA_PRDCCION <= to_date('30/04/2025', 'dd/mm/yyyy')
  AND ((CER_NMRO_CRTFCDO, CER_NMRO_PLZA) IN
       (SELECT A.EST_SLCTUD, A.EST_PLZA
        FROM ESTADO_CTA_RCBOS A
        WHERE A.EST_ESTDO_RCBO = 'I'
          AND A.EST_ORGEN_RCDO = 'P'
          AND A.EST_FCHA_MRA IS NULL
          AND A.EST_FCHA_MVTO > to_date('30/04/2025', 'dd/mm/yyyy')))
  AND POL_TPOPLZA = 'C'
  AND CER_ESTDO_PRDCCION NOT IN ('00','70','80', '50')
  AND CER_RAM_CDGO = POL_RAM_CDGO
  AND CER_CLSE_PLZA = POL_CDGO_CLSE
  AND CER_NMRO_PLZA = POL_NMRO_PLZA
  AND CER_FCHA_PRDCCION < to_date('30/04/2025', 'dd/mm/yyyy') - 75
  AND CRTFCDOS.CER_NMRO_PLZA = 1143
GROUP BY CER_NMRO_PLZA
ORDER BY CER_NMRO_PLZA;

SELECT CER_NMRO_PLZA, CER_FCHA_PRDCCION FECHA, CER_FCHA_DSDE_ACTUAL, CER_NMRO_CRTFCDO
FROM CRTFCDOS, PLZAS
WHERE CER_VLOR_SLDO > 2
  AND CER_FCHA_PRDCCION >= to_date('01/01/1900', 'dd/mm/yyyy')
  AND CER_FCHA_PRDCCION <= to_date('30/04/2025', 'dd/mm/yyyy')
  AND POL_TPOPLZA = 'C'
  AND CER_ESTDO_PRDCCION NOT IN ('00','70','80')
  AND CER_RAM_CDGO = POL_RAM_CDGO
  AND CER_CLSE_PLZA = POL_CDGO_CLSE
  AND CER_NMRO_PLZA = POL_NMRO_PLZA
  AND CER_FCHA_PRDCCION < to_date('30/04/2025', 'dd/mm/yyyy') - 75
  AND CRTFCDOS.CER_NMRO_PLZA = 1143



select s.CER_VLOR_TTAL_CRTFCDO, s.CER_VLOR_SLDO, s.CER_ESTDO_PRDCCION, s.*
from CRTFCDOS s
where s.CER_NMRO_CRTFCDO in ('2146412', '1640836', '1639121');

select s.CER_VLOR_TTAL_CRTFCDO, s.CER_VLOR_SLDO, s.CER_ESTDO_PRDCCION, s.*
from CRTFCDOS s
where s.CER_NMRO_CRTFCDO in ('2022911','2149927','2152750','2158493');

select * from estado_cta_rcbos where est_slctud in (2030451);

SELECT PLZAS.POL_SUC_CIA_CDGO COD_CIA,
       SCRSL.SUC_CDGO SUCURSAL,
       PLZAS.POL_NMRO_PLZA Poliza,
       CRTFCDOS.CER_NMRO_CRTFCDO NumCert,
       CRTFCDOS.CER_FCHA_DSDE_ACTUAL FECHA_CER,
       (SUM(NVL(CRTFCDOS.CER_GSTOS_EXPDCION, 0) +
            CRTFCDOS.CER_VLOR_IVA +
            CRTFCDOS.CER_VLOR_PRMA_NTA +
            CRTFCDOS.CER_VLOR_PPLRIA +
            NVL(CRTFCDOS.CER_VLOR_CTA_FAX, 0) +
            NVL(CRTFCDOS.CER_VLOR_CTA_PRMA, 0)) / COUNT(9)) -
       (SUM(DECODE(ESTADO_CTA_RCBOS.EST_CDGO_CNCPTO, 'PRM',
                   ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'GSE',
                   ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'IVA',
                   ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CPL',
                   ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CFI',
                   ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CFX',
                   ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 0))) AS DIFERENCIA
FROM PLZAS, CRTFCDOS, SCRSL, ESTADO_CTA_RCBOS, CRTFCDO_ANLDO
WHERE CRTFCDOS.CER_VLOR_SLDO > 2
  AND CRTFCDOS.CER_NMRO_PLZA = 1143
  AND CRTFCDOS.CER_ESTDO_PRDCCION NOT IN ('00','70','80')
  AND ESTADO_CTA_RCBOS.EST_ESTDO_RCBO(+) = 'I'
  AND ESTADO_CTA_RCBOS.EST_ORGEN_RCDO(+) = 'P'
  AND ESTADO_CTA_RCBOS.EST_FCHA_MRA(+) IS NULL
  AND ESTADO_CTA_RCBOS.EST_FCHA_MVTO(+) BETWEEN to_date('01/01/1900', 'dd/mm/yyyy') AND (to_date('30/04/2025', 'dd/mm/yyyy') + 1)
  AND ((PLZAS.POL_SUC_CIA_CDGO = SCRSL.SUC_CIA_CDGO)
    AND (PLZAS.POL_SUC_CDGO = SCRSL.SUC_CDGO)
    AND (PLZAS.POL_TPOPLZA = 'C')
    AND (CRTFCDOS.CER_RAM_CDGO = PLZAS.POL_RAM_CDGO)
    AND (CRTFCDOS.CER_CLSE_PLZA = PLZAS.POL_CDGO_CLSE)
    AND (CRTFCDOS.CER_NMRO_PLZA = PLZAS.POL_NMRO_PLZA)
    AND (ESTADO_CTA_RCBOS.EST_SLCTUD(+) = CRTFCDOS.CER_NMRO_CRTFCDO)
    AND (ESTADO_CTA_RCBOS.EST_PLZA(+) = CRTFCDOS.CER_NMRO_PLZA)
    AND (CRTFCDO_ANLDO.CER_NMRO_CRTFCDO(+) = CRTFCDOS.CER_NMRO_CRTFCDO)
    AND (CRTFCDO_ANLDO.CER_NMRO_PLZA(+) = CRTFCDOS.CER_NMRO_PLZA)
    AND (CRTFCDO_ANLDO.CER_CLSE_PLZA(+) = CRTFCDOS.CER_CLSE_PLZA)
    AND (CRTFCDO_ANLDO.CER_RAM_CDGO(+) = CRTFCDOS.CER_RAM_CDGO))
GROUP BY PLZAS.POL_SUC_CIA_CDGO,
         SCRSL.SUC_CDGO,
         PLZAS.POL_NMRO_PLZA,
         CRTFCDOS.CER_NMRO_CRTFCDO,
         CRTFCDOS.CER_FCHA_DSDE_ACTUAL
ORDER BY DIFERENCIA DESC;

----ESTADOS DE CERTIFICADOS
select *
--DISTINCT RV_DOMAIN
from cg_ref_codes c
where rv_domain like '%ESTADO_PRODUCCION%';

select s.CER_VLOR_TTAL_CRTFCDO, s.CER_VLOR_SLDO, s.CER_ESTDO_PRDCCION, s.*
from CRTFCDOS s
where s.CER_NMRO_CRTFCDO in (
                             2030451,
                             2022828,
                             1687958,
                             2022911,
                             2005416,
                             2017216,
                             2012164,
                             2013012
    );

select * from PRVSION_PRMAS where PRO_FCHA_CRCION > to_date('2025-01-02', 'YYYY-MM-DD');

select *
from PRVSION_PRMAS
where PRO_NMRO_CRTFCDO in (2175756,
                           2175786,
                           2175799,
                           2175889,
                           2175905,
                           2175913,
                           2176189,
                           2176192,
                           2173887,
                           2173892,
                           2173914,
                           2173927,
                           2173928,
                           2173960,
                           2174012,
                           2174114,
                           2174213,
                           2174250,
                           2174252,
                           2174275,
                           2170349,
                           2174344,
                           2174373,
                           2174424,
                           2174450,
                           2174508,
                           2174567,
                           2174579,
                           2174601,
                           2175455,
                           2175515,
                           2175524,
                           2175531,
                           2171536,
                           2175536,
                           2175540,
                           2171566,
                           2175566,
                           2171610,
                           2175610,
                           2175695,
                           2175205,
                           2175245,
                           2175315,
                           2175337,
                           2171343,
                           2175340,
                           2175417,
                           2174970,
                           2174996,
                           2175008,
                           2175010,
                           2175088
    );


