SELECT C.VR_INDEMNIZABLE,
       C.VR_DEDUCIBLE,
       C.VR_AINDEMNIZAR,
       C.VR_CARTERA,
       (C.VR_AINDEMNIZAR - C.VR_CARTERA) AS TOTAL_A_INDEMNIZAR,
       C.COD_COBERTURA || '-' || D.TXT_COB AS COD_COBERTURA
FROM SIM_DATOS_CALCULADORA_SINI C
INNER JOIN A1002100 D ON C.COD_CIA = D.COD_CIA AND C.COD_PRODUCTO = D.COD_RAMO AND C.COD_COBERTURA = D.COD_COB
WHERE C.COD_CIA = 3
    AND C.COD_SECC = 23
    AND C.COD_PRODUCTO = 117
    AND C.NUM_POL1 = 2782000005512
    AND C.IDSECUENCIA = 227;


select * from a1002100 where COD_COB in(350) and COD_RAMO = 117;

SELECT parameter, value
FROM nls_database_parameters
WHERE parameter LIKE 'NLS_CHARACTERSET';

select * from A1002100 where COD_RAMO = 130

SELECT username, account_status, password_versions
FROM dba_users
WHERE username = 'ops$puma';
