SELECT PP.NUM_POL1 ,
       A20D.COD_RIES ,
       DECODE(A20D.VALOR_CAMPO,'F','FULL','BÁSICO') CYBER_RISK ,
       PP.TDOC_TERCERO ,
       PP.NRO_DOCUMTO ,
       PCK999_TERCEROS.FUN_RETORNA_NOMBRES(PP.NRO_DOCUMTO,TDOC_TERCERO,NULL) NOMBRES,
       NN.TIPO_DOCUMTO ,
       NN.NRO_DOCUMTO  DOC_BENEF,
       NN.NOMBRE || ' ' ||
       NN.APELLIDO NOM_BENEF,
       TO_CHAR(PP.FECHA_VIG_POL,'DD-MM-YYYY')   FECHA_VIG_POL,
       TO_CHAR(PP.FECHA_VENC_POL,'DD-MM-YYYY')  FECHA_VENC_POL
FROM A2000020 A20D,
     A2000030 PP,
     A9990100 NN
WHERE PP.NUM_SECU_POL = A20D.NUM_SECU_POL
  AND   A20D.NUM_SECU_POL = NN.NUM_SECU_POL
  AND PP.NUM_POL1      IS NOT NULL
  AND A20D.COD_CAMPO    = 'CYBER_RISK'
  AND NN.NOMINA         ='DAVI'
  AND NVL(MCA_BAJA,'N') = 'N'
  AND A20D.COD_RIES     = NN.COD_RIES
  AND PP.NUM_END      = ( SELECT MAX(C.NUM_END) FROM A2000030 C
                          WHERE C.NUM_SECU_POL = PP.NUM_SECU_POL)

  AND NN.NUM_END      = (SELECT MAX(NUM_END) FROM A9990100
                         WHERE NUM_SECU_POL = PP.NUM_SECU_POL
                           AND COD_RIES =  A20D.COD_RIES
                           AND NOMINA   = 'DAVI'
                           AND NVL(MCA_BAJA,'N') = 'N')

  AND A20D.NUM_END      = (SELECT MAX(NUM_END) FROM A2000020
                           WHERE NUM_SECU_POL = PP.NUM_SECU_POL
                             AND COD_RIES =  A20D.COD_RIES
                             AND COD_CAMPO = 'CYBER_RISK'
                             AND NVL(VALOR_CAMPO,'Z') <> 'Z')

  AND A20D.VALOR_CAMPO  IN ('B','F')
  AND PP.NUM_END        =
      (SELECT MAX(SA.NUM_END)
       FROM A2000030 SA
       WHERE SA.NUM_POL1 = PP.NUM_POL1
         AND SA.COD_CIA    = PP.COD_CIA
         AND SA.COD_SECC   = PP.COD_SECC
         AND SA.COD_RAMO   = PP.COD_RAMO
      )
  AND PP.FECHA_EMI_END BETWEEN TO_DATE('01-12-2021','DD-MM-YYYY') AND TO_DATE('25-02-2022','DD-MM-YYYY')
  AND PP.COD_CIA  = 3
  AND PP.COD_SECC = 23
  AND PP.COD_RAMO = 109
ORDER BY PP.NUM_POL1,
         A20D.COD_RIES