select *
from INDEMNIZA.SINIESTRO;

SELECT
    SOLICITUD_SAI_SOLICITUD,
    FEC_REP,
    TO_CHAR(FEC_REP, 'DD/MM/YYYY HH24:MI:SS') AS FEC_REP_FORMATEADO,
    CASE
        WHEN TO_CHAR(FEC_REP, 'HH24:MI:SS') = '00:00:00' THEN 'Sin hora (00:00:00)'
        WHEN FEC_REP IS NULL THEN 'NULL'
        ELSE 'Con hora'
        END AS ESTADO_HORA
FROM
    INDEMNIZA.SINIESTRO
WHERE
    FEC_REP IS NOT NULL
  AND TO_CHAR(FEC_REP, 'HH24:MI:SS') = '00:00:00'
ORDER BY
    FEC_REP;