SELECT *
FROM CDGOS_RSLTDS C
WHERE c.cre_tpo_rsltdo ='03';

SELECT *
FROM cdgos_rsltds C
WHERE c.cre_tpo_rsltdo = '03'
  and c.CRE_CNSLTBLE = 'S';

SELECT C.CRE_CDGO, C.CRE_TPO_RSLTDO, C.CRE_CNSLTBLE, C.*
FROM CDGOS_RSLTDS C
WHERE c.CRE_CDGO ='115';

SELECT decode(a.arr_tpo_arrndtrio,'I','INQUILINO','P','INQUILINO','DEUDOR SOLIDARIO') AS TIPO_DEUDOR,
       a.arr_nmro_idntfccion  AS IDENTIFICACION,
       pk_terceros.f_nombres(a.arr_nmro_idntfccion, a.arr_tpo_idntfccion) AS NOMBRE,
       r.ret_nmro_slctud AS SOLICITUD,
       r.ret_cdgo_rsltdo AS CODIGO_RESULTADO,
       r.ret_obsrvcion   AS DESCRIPCION_RESULTADO
FROM arrndtrios a,rsltdo_estdio r,cg_ref_codes g
WHERE a.arr_ses_nmro    = 10978372
  and a.arr_estdo = 'V'
  and a.arr_nmro_slctud = r.ret_nmro_slctud
  and g.rv_low_value = r.ret_cdgo_rsltdo
  and g.rv_domain = 'RESULTADOS'
  and g.rv_high_value  ='A'
UNION
SELECT
    DECODE(a.arr_tpo_arrndtrio, 'I', 'INQUILINO', 'P', 'INQUILINO', 'DEUDOR SOLIDARIO') AS TIPO_DEUDOR,
    a.arr_nmro_idntfccion AS IDENTIFICACION,
    pk_terceros.f_nombres(a.arr_nmro_idntfccion, a.arr_tpo_idntfccion) AS NOMBRE,
    r.ret_nmro_slctud AS SOLICITUD,
    r.ret_cdgo_rsltdo AS CODIGO_RESULTADO,
    r.ret_obsrvcion AS DESCRIPCION_RESULTADO
FROM arrndtrios a
         INNER JOIN rsltdo_estdio r ON a.arr_nmro_slctud = r.ret_nmro_slctud
         INNER JOIN cdgos_rsltds c ON r.ret_cdgo_rsltdo = c.cre_cdgo
WHERE a.arr_ses_nmro = 10978372
  AND a.arr_estdo = 'V'
  AND c.cre_cnsltble = 'S'
  AND c.cre_tpo_rsltdo IN (SELECT r.ret_cdgo_rsltdo
                           FROM arrndtrios a
                                    INNER JOIN rsltdo_estdio r ON a.arr_nmro_slctud = r.ret_nmro_slctud
                                    INNER JOIN cg_ref_codes g ON g.rv_low_value = r.ret_cdgo_rsltdo
                           WHERE a.arr_ses_nmro = 10978372
                             AND a.arr_estdo = 'V'
                             AND g.rv_domain = 'RESULTADOS'
                             AND g.rv_high_value = 'A' group by r.ret_cdgo_rsltdo);


SELECT RET_NMRO_SLCTUD
FROM rsltdo_estdio
WHERE RET_CDGO_RSLTDO IN ('115', '01')
GROUP BY RET_NMRO_SLCTUD
HAVING COUNT(DISTINCT RET_CDGO_RSLTDO) = 2;

---10978372 03 115
---10233811 01 115

select r.rea_tpo_rsltdo, r.* from rsltdos_arrndtrios r where REA_NMRO_SLCTUD = 10978372;

SELECT S.SES_NMRO AS SOLICITUD,
       S.SES_NMRO_PLZA AS POLIZA,
       A.ARR_NMRO_IDNTFCCION AS IDENTIFICACION_INQUILINO,
       A.ARR_TPO_IDNTFCCION AS TIPO_IDENTIFICACION,
       PK_TERCEROS.F_NOMBRES(A.ARR_NMRO_IDNTFCCION, A.ARR_TPO_IDNTFCCION) AS NOMBRE_INQUILINO,
       DECODE(D.CORREO,NULL,PK_TERCEROS.FUN_RET_MEDIO_TERCERO(A.ARR_TPO_IDNTFCCION,A.ARR_NMRO_IDNTFCCION,NULL,6),D.CORREO) AS CORREO_INQUILINO ,
       DECODE(D.NUM_TELEFONO,NULL,PK_TERCEROS.FUN_RET_MEDIO_TERCERO(A.ARR_TPO_IDNTFCCION,A.ARR_NMRO_IDNTFCCION,NULL,4),D.NUM_TELEFONO) AS TELEFONO_INQUILINO,
       S.SES_CNON_ARRNDMNTO AS CANON,
       S.SES_CTA_ADMNSTRCION AS CUOTA,
       R.DI_DIRECCION AS DIRECCION_INMUEBLE,
       C.RV_MEANING AS DESTINO_INMUEBLE,
       P.NOMBRE AS CIUDAD_INMUEBLE,
       R.RET_CDGO_RSLTDO AS CODIGO_RESULTADO,
       DECODE(R.RET_CDGO_RSLTDO,'01','APROBADA','02','APLAZADA','03','NEGADA') AS ESTADO_GENERAL,
       R.RET_OBSRVCION AS RESULTADO_ESTUDIO,
       TO_CHAR(S.SES_FCHA_INGRSO,'DDMMYYYY HH:MM:SS') FECHA_RADICACION,
       TO_CHAR(R.RET_FCHA_RSLTDO,'DDMMYYYY HH:MM:SS') FECHA_RESULTADO
FROM SLCTDES_ESTDIOS S
    LEFT JOIN AEW_DEUDORES D ON S.SES_NMRO = D.SOLICITUD AND D.TIPO = 'I'
    LEFT JOIN AEW_ESTUDIOS E ON S.SES_NMRO = E.SOLICITUD
    INNER JOIN DIRECCIONES R ON S.SES_NMRO = R.DI_SOLICITUD AND R.DI_TPO_DRCCION = 'E'
    INNER JOIN RSLTDO_ESTDIO R ON (S.SES_NMRO = R.RET_NMRO_SLCTUD )
    INNER JOIN ARRNDTRIOS A ON (S.SES_NMRO = A.ARR_NMRO_SLCTUD)
    INNER JOIN DIVISION_POLITICAS P ON  R.DI_DIVPOL_CODIGO = P.CODIGO_CODAZZI
    INNER JOIN CG_REF_CODES C ON S.SES_DSTNO_INMBLE = C.RV_LOW_VALUE AND C.RV_DOMAIN ='DESTINO_INMUEBLE'
WHERE S.SES_NMRO_PLZA = 249
  AND TRUNC(S.SES_FCHA_INGRSO) >= to_date('01/02/2025', 'dd/mm/yyyy')
  AND TRUNC(S.SES_FCHA_INGRSO) <= to_date('31/12/2025', 'dd/mm/yyyy')
UNION
SELECT W.SOLICITUD AS SOLICITUD,
       W.COD_INMOBILIARIA AS POLIZA,
       D.NUM_DOCUMENTO AS IDENTIFICACION_INQUILINO,
       D.TIP_DOCUMENTO AS TIPO_IDENTIFICACION,
       D.PNOMBRE||' '||D.SNOMBRE||' '||D.PAPELLIDO||' '||D.SAPELLIDO AS NOMBRE_INQUILINO,
       D.CORREO AS CORREO_INQUILINO ,
       D.NUM_TELEFONO AS TELEFONO_INQUILINO,
       W.VLR_CANON AS CANON,
       W.VLR_ADMIN AS CUOTA,
       W.DIRECCION AS DIRECCION_INMUEBLE,
       C.RV_MEANING AS DESTINO_INMUEBLE,
       P.NOMBRE AS CIUDAD_INMUEBLE,
       R.COD_PRINCIPAL AS CODIGO_RESULTADO,
       DECODE(R.COD_PRINCIPAL,'01','APROBADA','02','APLAZADA','03','NEGADA') AS ESTADO_GENERAL,
       R.DESC_COD_SECUNDARIO AS RESULTADO_ESTUDIO,
       TO_CHAR(W.FEC_DILIGENCIA,'DDMMYYYY HH:MM:SS') FECHA_RADICACION,
       TO_CHAR(W.FEC_MODIFICA,'DDMMYYYY HH:MM:SS') FECHA_RESULTADO
FROM AEW_ESTUDIOS W
         LEFT JOIN AEW_DEUDORES D ON W.SOLICITUD = D.SOLICITUD AND D.TIPO = 'I'
         INNER JOIN DIVISION_POLITICAS P ON  W.CIUDAD = P.CODIGO_CODAZZI
         INNER JOIN CG_REF_CODES C ON W.DESTINO = C.RV_LOW_VALUE AND C.RV_DOMAIN ='DESTINO_INMUEBLE'
         LEFT JOIN AEW_RESULTADOS_ESTUDIO R ON W.SOLICITUD = R.SOLICITUD
WHERE W.COD_INMOBILIARIA = 249
  AND TRUNC(W.FEC_DILIGENCIA) >= to_date('01/02/2025', 'dd/mm/yyyy')
  AND TRUNC(W.FEC_DILIGENCIA) <= to_date('31/12/2025', 'dd/mm/yyyy')
  AND NOT EXISTS (SELECT *
                  FROM RSLTDOS_ARRNDTRIOS T
                  WHERE T.REA_NMRO_SLCTUD = W.SOLICITUD
                    AND T.REA_TPO_RSLTDO='D')
  AND NOT EXISTS (SELECT *
                  FROM SLCTDES_ESTDIOS S
                  WHERE S.SES_NMRO = W.SOLICITUD)
  ORDER BY FECHA_RESULTADO, CODIGO_RESULTADO ASC;

select * from SLCTDES_ESTDIOS where SES_FCHA_INGRSO >= to_date('01/01/2025', 'dd/mm/yyyy');
select * from RSLTDO_ESTDIO;

SELECT * FROM RSLTDO_ESTDIO R WHERE RET_NMRO_SLCTUD = 11085865;
select * from SLCTDES_ESTDIOS where SES_NMRO = 385538;

SELECT *
FROM AEW_RESULTADOS_ESTUDIO ARS
where ars.solicitud = 11085865;

---ARR_TPO_ARRNDTRIO IN ('I', 'C', 'P', 'D', 'R')
select * from arrndtrios where ARR_SES_NMRO = 385538;
select * from arrndtrios where ARR_SES_NMRO = 6150822;

SELECT * FROM RSLTDO_ESTDIO R WHERE RET_NMRO_SLCTUD in (6150823);


-- Consulta para el solicitante principal (tipo 'P')
SELECT
    S.SES_NMRO AS SOLICITUD,
    S.SES_NMRO_PLZA AS POLIZA,
    A.ARR_NMRO_IDNTFCCION AS IDENTIFICACION_INQUILINO,
    A.ARR_TPO_IDNTFCCION AS TIPO_IDENTIFICACION,
    PK_TERCEROS.F_NOMBRES(A.ARR_NMRO_IDNTFCCION, A.ARR_TPO_IDNTFCCION) AS NOMBRE_INQUILINO,
    DECODE(D.CORREO, NULL, PK_TERCEROS.FUN_RET_MEDIO_TERCERO(A.ARR_TPO_IDNTFCCION, A.ARR_NMRO_IDNTFCCION, NULL, 6), D.CORREO) AS CORREO_INQUILINO,
    DECODE(D.NUM_TELEFONO, NULL, PK_TERCEROS.FUN_RET_MEDIO_TERCERO(A.ARR_TPO_IDNTFCCION, A.ARR_NMRO_IDNTFCCION, NULL, 4), D.NUM_TELEFONO) AS TELEFONO_INQUILINO,
    S.SES_CNON_ARRNDMNTO AS CANON,
    S.SES_CTA_ADMNSTRCION AS CUOTA,
    R.DI_DIRECCION AS DIRECCION_INMUEBLE,
    C.RV_MEANING AS DESTINO_INMUEBLE,
    P.NOMBRE AS CIUDAD_INMUEBLE,
    RES.RET_CDGO_RSLTDO AS CODIGO_RESULTADO,
    DECODE(RES.RET_CDGO_RSLTDO, '01', 'APROBADA', '02', 'APLAZADA', '03', 'NEGADA') AS ESTADO_GENERAL,
    RES.RET_OBSRVCION AS RESULTADO_ESTUDIO,
    TO_CHAR(S.SES_FCHA_INGRSO, 'DDMMYYYY HH:MM:SS') AS FECHA_RADICACION,
    TO_CHAR(RES.RET_FCHA_RSLTDO, 'DDMMYYYY HH:MM:SS') AS FECHA_RESULTADO,
    'Principal' AS TIPO
FROM SLCTDES_ESTDIOS S
         LEFT JOIN AEW_DEUDORES D ON S.SES_NMRO = D.SOLICITUD AND D.TIPO = 'I'
         LEFT JOIN AEW_ESTUDIOS E ON S.SES_NMRO = E.SOLICITUD
         INNER JOIN DIRECCIONES R ON S.SES_NMRO = R.DI_SOLICITUD AND R.DI_TPO_DRCCION = 'E'
         INNER JOIN RSLTDO_ESTDIO RES ON S.SES_NMRO = RES.RET_NMRO_SLCTUD
         INNER JOIN ARRNDTRIOS A ON S.SES_NMRO = A.ARR_SES_NMRO AND A.ARR_TPO_ARRNDTRIO IN ('P', 'I')
         INNER JOIN DIVISION_POLITICAS P ON R.DI_DIVPOL_CODIGO = P.CODIGO_CODAZZI
         INNER JOIN CG_REF_CODES C ON S.SES_DSTNO_INMBLE = C.RV_LOW_VALUE AND C.RV_DOMAIN = 'DESTINO_INMUEBLE'
WHERE S.SES_NMRO_PLZA = 141
  AND TRUNC(S.SES_FCHA_INGRSO) BETWEEN TO_DATE('01/01/2018', 'dd/mm/yyyy')
    AND TO_DATE('31/12/2025', 'dd/mm/yyyy')

UNION ALL

-- Consulta para los codeudores (tipo 'C')
SELECT
    S.SES_NMRO AS SOLICITUD,
    S.SES_NMRO_PLZA AS POLIZA,
    A.ARR_NMRO_IDNTFCCION AS IDENTIFICACION_INQUILINO,
    A.ARR_TPO_IDNTFCCION AS TIPO_IDENTIFICACION,
    PK_TERCEROS.F_NOMBRES(A.ARR_NMRO_IDNTFCCION, A.ARR_TPO_IDNTFCCION) AS NOMBRE_INQUILINO,
    DECODE(D.CORREO, NULL, PK_TERCEROS.FUN_RET_MEDIO_TERCERO(A.ARR_TPO_IDNTFCCION, A.ARR_NMRO_IDNTFCCION, NULL, 6), D.CORREO) AS CORREO_INQUILINO,
    DECODE(D.NUM_TELEFONO, NULL, PK_TERCEROS.FUN_RET_MEDIO_TERCERO(A.ARR_TPO_IDNTFCCION, A.ARR_NMRO_IDNTFCCION, NULL, 4), D.NUM_TELEFONO) AS TELEFONO_INQUILINO,
    S.SES_CNON_ARRNDMNTO AS CANON,
    S.SES_CTA_ADMNSTRCION AS CUOTA,
    R.DI_DIRECCION AS DIRECCION_INMUEBLE,
    C.RV_MEANING AS DESTINO_INMUEBLE,
    P.NOMBRE AS CIUDAD_INMUEBLE,
    RES.RET_CDGO_RSLTDO AS CODIGO_RESULTADO,
    DECODE(RES.RET_CDGO_RSLTDO, '01', 'APROBADA', '02', 'APLAZADA', '03', 'NEGADA') AS ESTADO_GENERAL,
    RES.RET_OBSRVCION AS RESULTADO_ESTUDIO,
    TO_CHAR(S.SES_FCHA_INGRSO, 'DDMMYYYY HH:MM:SS') AS FECHA_RADICACION,
    TO_CHAR(RES.RET_FCHA_RSLTDO, 'DDMMYYYY HH:MM:SS') AS FECHA_RESULTADO,
    'Codeudor' AS TIPO
FROM SLCTDES_ESTDIOS S
         LEFT JOIN AEW_DEUDORES D ON S.SES_NMRO = D.SOLICITUD AND D.TIPO = 'I'
         LEFT JOIN AEW_ESTUDIOS E ON S.SES_NMRO = E.SOLICITUD
         INNER JOIN DIRECCIONES R ON S.SES_NMRO = R.DI_SOLICITUD AND R.DI_TPO_DRCCION = 'E'
         INNER JOIN ARRNDTRIOS A ON S.SES_NMRO = A.ARR_SES_NMRO AND A.ARR_TPO_ARRNDTRIO IN ('C', 'D')
    -- Para los codeudores, el estudio se obtiene según el número de solicitud del codeudor
         INNER JOIN RSLTDO_ESTDIO RES ON A.ARR_NMRO_SLCTUD = RES.RET_NMRO_SLCTUD
         INNER JOIN DIVISION_POLITICAS P ON R.DI_DIVPOL_CODIGO = P.CODIGO_CODAZZI
         INNER JOIN CG_REF_CODES C ON S.SES_DSTNO_INMBLE = C.RV_LOW_VALUE AND C.RV_DOMAIN = 'DESTINO_INMUEBLE'
WHERE S.SES_NMRO_PLZA = 141
  AND TRUNC(S.SES_FCHA_INGRSO) BETWEEN TO_DATE('01/01/2018', 'dd/mm/yyyy')
    AND TO_DATE('31/12/2025', 'dd/mm/yyyy')
ORDER BY SOLICITUD, TIPO desc, CODIGO_RESULTADO ASC;



SELECT S.SES_NMRO AS SOLICITUD,
                   S.SES_NMRO_PLZA AS POLIZA,
                   A.ARR_NMRO_IDNTFCCION AS IDENTIFICACION_INQUILINO,
                   A.ARR_TPO_IDNTFCCION AS TIPO_IDENTIFICACION,
                   PK_TERCEROS.F_NOMBRES(A.ARR_NMRO_IDNTFCCION, A.ARR_TPO_IDNTFCCION) AS NOMBRE_INQUILINO,
                   DECODE(D.CORREO,NULL,PK_TERCEROS.FUN_RET_MEDIO_TERCERO(A.ARR_TPO_IDNTFCCION,A.ARR_NMRO_IDNTFCCION,NULL,6),D.CORREO) AS CORREO_INQUILINO ,
                   DECODE(D.NUM_TELEFONO,NULL,PK_TERCEROS.FUN_RET_MEDIO_TERCERO(A.ARR_TPO_IDNTFCCION,A.ARR_NMRO_IDNTFCCION,NULL,4),D.NUM_TELEFONO) AS TELEFONO_INQUILINO,
                   D.INGRESOS,
                   D.FECHA_EXPEDICION,
                   S.SES_CNON_ARRNDMNTO AS CANON,
                   S.SES_CTA_ADMNSTRCION AS CUOTA,
                   DIR.DI_DIRECCION AS DIRECCION_INMUEBLE,
                   C.RV_MEANING AS DESTINO_INMUEBLE,
                   P.NOMBRE AS CIUDAD_INMUEBLE,
                   E.NOMBRE_ASESOR,
                   E.CORREO_ASESOR,
                   DECODE(RES.RET_CDGO_RSLTDO,'01','APROBADA','02','APLAZADA','03','NEGADA') AS ESTADO_GENERAL,
                   TO_CHAR(S.SES_FCHA_INGRSO,'DDMMYYYY HH:MM:SS') FECHA_RADICACION,
                   TO_CHAR(RES.RET_FCHA_RSLTDO,'DDMMYYYY HH:MM:SS') FECHA_RESULTADO
              FROM SLCTDES_ESTDIOS S
              LEFT JOIN AEW_DEUDORES D ON S.SES_NMRO = D.SOLICITUD AND D.TIPO = 'I'
              LEFT JOIN AEW_ESTUDIOS E ON S.SES_NMRO = E.SOLICITUD
              INNER JOIN DIRECCIONES DIR ON S.SES_NMRO = DIR.DI_SOLICITUD AND DIR.DI_TPO_DRCCION = 'E'
              INNER JOIN RSLTDO_ESTDIO RES ON (S.SES_NMRO = RES.RET_NMRO_SLCTUD AND RES.RET_CDGO_RSLTDO IN ('01','02','03'))
              INNER JOIN ARRNDTRIOS A ON (S.SES_NMRO = A.ARR_NMRO_SLCTUD)
              INNER JOIN DIVISION_POLITICAS P ON  DIR.DI_DIVPOL_CODIGO = P.CODIGO_CODAZZI
              INNER JOIN CG_REF_CODES C ON S.SES_DSTNO_INMBLE = C.RV_LOW_VALUE AND C.RV_DOMAIN ='DESTINO_INMUEBLE'
              WHERE S.SES_NMRO_PLZA = 13057
                AND TRUNC(S.SES_FCHA_INGRSO) >= to_date('24/01/2026', 'dd/mm/yyyy')
                AND TRUNC(S.SES_FCHA_INGRSO) <= to_date('27/01/2026', 'dd/mm/yyyy')
            UNION
            SELECT W.SOLICITUD AS SOLICITUD,
                   W.COD_INMOBILIARIA AS POLIZA,
                   D.NUM_DOCUMENTO AS IDENTIFICACION_INQUILINO,
                   D.TIP_DOCUMENTO AS TIPO_IDENTIFICACION,
                   D.PNOMBRE||' '||D.SNOMBRE||' '||D.PAPELLIDO||' '||D.SAPELLIDO AS NOMBRE_INQUILINO,
                   D.CORREO AS CORREO_INQUILINO ,
                   D.NUM_TELEFONO AS TELEFONO_INQUILINO,
                   D.INGRESOS,
                   D.FECHA_EXPEDICION,
                   W.VLR_CANON AS CANON,
                   W.VLR_ADMIN AS CUOTA,
                   W.DIRECCION AS DIRECCION_INMUEBLE,
                   C.RV_MEANING AS DESTINO_INMUEBLE,
                   P.NOMBRE AS CIUDAD_INMUEBLE,
                   W.NOMBRE_ASESOR,
                   W.CORREO_ASESOR,
                   'APLAZADO-NUBE' AS ESTADO_GENERAL,
                   TO_CHAR(W.FEC_DILIGENCIA,'DDMMYYYY HH:MM:SS') FECHA_RADICACION,
                   TO_CHAR(W.FEC_MODIFICA,'DDMMYYYY HH:MM:SS') FECHA_RESULTADO
              FROM AEW_ESTUDIOS W
              LEFT JOIN AEW_DEUDORES D ON W.SOLICITUD = D.SOLICITUD AND D.TIPO = 'I'
              INNER JOIN DIVISION_POLITICAS P ON  W.CIUDAD = P.CODIGO_CODAZZI
              INNER JOIN CG_REF_CODES C ON W.DESTINO = C.RV_LOW_VALUE AND C.RV_DOMAIN ='DESTINO_INMUEBLE'
              WHERE W.COD_INMOBILIARIA = 13057
                AND TRUNC(W.FEC_DILIGENCIA) >= to_date('24/01/2026', 'dd/mm/yyyy')
                AND TRUNC(W.FEC_DILIGENCIA) <= to_date('27/01/2026', 'dd/mm/yyyy')
                AND NOT EXISTS (SELECT *
                FROM RSLTDOS_ARRNDTRIOS T
                WHERE T.REA_NMRO_SLCTUD = W.SOLICITUD
                AND T.REA_TPO_RSLTDO='D')
                AND NOT EXISTS (SELECT *
                FROM SLCTDES_ESTDIOS S
                WHERE S.SES_NMRO = W.SOLICITUD)

