---procedure PROVISION_PRIMAS
SELECT ALL PLZAS.POL_SUC_CIA_CDGO COD_CIA,
           SCRSL.SUC_CDGO SUCURSAL,
           PLZAS.POL_NMRO_PLZA Poliza,
           PLZAS.POL_PRS_TPO_IDNTFCCION TIPO_IDEN,
           PLZAS.POL_PRS_NMRO_IDNTFCCION Identificacion,
           INITCAP(PK_TERCEROS.F_NOMBRES(PLZAS.POL_PRS_NMRO_IDNTFCCION,
                                         PLZAS.POL_PRS_TPO_IDNTFCCION)) NombrePoliza,
           PLZAS.POL_TPOPLZA TIPO_POLIZA,
           CRTFCDOS.CER_NMRO_CRTFCDO NumCert,
           CRTFCDOS.CER_CLSE_PLZA CLASE,
           CRTFCDOS.CER_RAM_CDGO RAMO,
           CRTFCDOS.CER_FCHA_DSDE_ACTUAL FECHA_CER,
           (SUM(NVL(CRTFCDOS.CER_VLOR_PRMA_TTAL, 0)) / COUNT(9)) -
           (SUM(DECODE(ESTADO_CTA_RCBOS.EST_CDGO_CNCPTO,'PRM',
                       ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO,'GSE',
                       ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO,'IVA',
                       ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO,0))) Prima
FROM PLZAS, CRTFCDOS, SCRSL, ESTADO_CTA_RCBOS, CRTFCDO_ANLDO
WHERE CRTFCDOS.CER_VLOR_SLDO > 2
  AND CRTFCDOS.CER_NMRO_PLZA = 1143
  AND CRTFCDOS.CER_FCHA_PRDCCION >= to_date('01/10/2011', 'dd/mm/yyyy')
  AND CRTFCDOS.CER_ESTDO_PRDCCION NOT IN ('00','70','80')
  AND ESTADO_CTA_RCBOS.EST_ESTDO_RCBO(+) = 'I'
  AND ESTADO_CTA_RCBOS.EST_ORGEN_RCDO(+) = 'P'
  AND ESTADO_CTA_RCBOS.EST_FCHA_MRA(+) IS NULL
  AND ESTADO_CTA_RCBOS.EST_FCHA_MVTO(+) BETWEEN to_date('01/01/1900', 'dd/mm/yyyy') AND (to_date('30/04/2025', 'dd/mm/yyyy') + 1)
  --AND (SCRSL.SUC_CDGO = NVL('2501', SCRSL.SUC_CDGO))
  AND ((PLZAS.POL_SUC_CIA_CDGO = SCRSL.SUC_CIA_CDGO)
    AND (PLZAS.POL_SUC_CDGO = SCRSL.SUC_CDGO)
    AND (PLZAS.POL_TPOPLZA = 'C')
    AND (CRTFCDOS.CER_RAM_CDGO = PLZAS.POL_RAM_CDGO)
    AND (CRTFCDOS.CER_CLSE_PLZA = PLZAS.POL_CDGO_CLSE)
    AND (CRTFCDOS.CER_NMRO_PLZA = PLZAS.POL_NMRO_PLZA)
    AND (ESTADO_CTA_RCBOS.EST_SLCTUD(+) = CRTFCDOS.CER_NMRO_CRTFCDO)
    AND (ESTADO_CTA_RCBOS.EST_PLZA(+) = CRTFCDOS.CER_NMRO_PLZA)
    AND (CRTFCDO_ANLDO.CER_NMRO_CRTFCDO(+) = CRTFCDOS.CER_NMRO_CRTFCDO)
    AND (CRTFCDO_ANLDO.CER_NMRO_PLZA(+) = CRTFCDOS.CER_NMRO_PLZA)
    AND (CRTFCDO_ANLDO.CER_CLSE_PLZA(+) = CRTFCDOS.CER_CLSE_PLZA)
    AND (CRTFCDO_ANLDO.CER_RAM_CDGO(+) = CRTFCDOS.CER_RAM_CDGO))
GROUP BY PLZAS.POL_SUC_CIA_CDGO,
         SCRSL.SUC_CDGO,
         PLZAS.POL_NMRO_PLZA,
         PLZAS.POL_PRS_TPO_IDNTFCCION,
         PLZAS.POL_PRS_NMRO_IDNTFCCION,
         INITCAP(PK_TERCEROS.F_NOMBRES(PLZAS.POL_PRS_NMRO_IDNTFCCION,
                                       PLZAS.POL_PRS_TPO_IDNTFCCION)),
         PLZAS.POL_TPOPLZA,
         CRTFCDOS.CER_NMRO_CRTFCDO,
         CRTFCDOS.CER_CLSE_PLZA,
         CRTFCDOS.CER_RAM_CDGO,
         CRTFCDOS.CER_FCHA_DSDE_ACTUAL
HAVING(SUM(NVL(CRTFCDOS.CER_GSTOS_EXPDCION, 0) +
           CRTFCDOS.CER_VLOR_IVA +
           CRTFCDOS.CER_VLOR_PRMA_NTA +
           CRTFCDOS.CER_VLOR_PPLRIA +
           NVL(CRTFCDOS.CER_VLOR_CTA_FAX, 0) +
           NVL(CRTFCDOS.CER_VLOR_CTA_PRMA, 0)) / COUNT(9)) -
      (SUM(DECODE(ESTADO_CTA_RCBOS.EST_CDGO_CNCPTO, 'PRM',
                  ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'GSE',
                  ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'IVA',
                  ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CPL',
                  ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CFI',
                  ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CFX',
                  ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 0))) > 0
UNION
SELECT ALL PLZAS.POL_SUC_CIA_CDGO COD_CIA,
           SCRSL.SUC_CDGO SUCURSAL,
           PLZAS.POL_NMRO_PLZA Poliza,
           PLZAS.POL_PRS_TPO_IDNTFCCION TIPO_IDEN,
           PLZAS.POL_PRS_NMRO_IDNTFCCION Identificacion,
           INITCAP(PK_TERCEROS.F_NOMBRES(PLZAS.POL_PRS_NMRO_IDNTFCCION,
                                         PLZAS.POL_PRS_TPO_IDNTFCCION)) NombrePoliza,
           PLZAS.POL_TPOPLZA TIPO_POLIZA,
           CRTFCDOS.CER_NMRO_CRTFCDO NumCert,
           CRTFCDOS.CER_CLSE_PLZA CLASE,
           CRTFCDOS.CER_RAM_CDGO RAMO,
           CRTFCDOS.CER_FCHA_DSDE_ACTUAL FECHA_CER,
           (SUM(NVL(CRTFCDOS.CER_VLOR_PRMA_TTAL, 0) +
                NVL(CRTFCDOS.CER_GSTOS_EXPDCION, 0)) / COUNT(9)) -
           (SUM(DECODE(ESTADO_CTA_RCBOS.EST_CDGO_CNCPTO,'PRM',
                       ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO,'GSE',
                       ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO,'IVA',
                       ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO,0))) Prima
FROM PLZAS,
     CRTFCDOS,
     SCRSL,
     ESTADO_CTA_RCBOS,
     CRTFCDO_ANLDO,
     CG_REF_CODES
WHERE (CRTFCDOS.CER_VLOR_SLDO > 2
    AND CRTFCDOS.CER_NMRO_PLZA = 1143
    AND CRTFCDOS.CER_FCHA_PRDCCION >= to_date('01/10/2011', 'dd/mm/yyyy')
    AND CRTFCDOS.CER_ESTDO_PRDCCION NOT IN ('00','70','80')
    AND ESTADO_CTA_RCBOS.EST_ESTDO_RCBO(+) = 'I'
    AND ESTADO_CTA_RCBOS.EST_ORGEN_RCDO(+) = 'P'
    AND ESTADO_CTA_RCBOS.EST_FCHA_MRA(+) IS NULL
    AND ESTADO_CTA_RCBOS.EST_FCHA_MVTO(+) BETWEEN to_date('01/01/1900', 'dd/mm/yyyy')
           AND (to_date('30/04/2025', 'dd/mm/yyyy') + 1) AND CG_REF_CODES.RV_DOMAIN = 'ESTADO_POLIZA')
  AND ((CRTFCDOS.CER_NMRO_CRTFCDO, CRTFCDOS.CER_NMRO_PLZA) IN
       (SELECT A.EST_SLCTUD, A.EST_PLZA
        FROM ESTADO_CTA_RCBOS A
        WHERE A.EST_ESTDO_RCBO = 'I'
          AND A.EST_ORGEN_RCDO = 'P'
          AND A.EST_FCHA_MRA IS NULL
          AND A.EST_FCHA_MVTO > to_date('30/04/2025', 'dd/mm/yyyy')))
  --AND (SCRSL.SUC_CDGO = NVL('2501', SCRSL.SUC_CDGO))
  AND ((PLZAS.POL_SUC_CIA_CDGO = SCRSL.SUC_CIA_CDGO)
    AND (PLZAS.POL_SUC_CDGO = SCRSL.SUC_CDGO)
    AND (PLZAS.POL_TPOPLZA = 'C')
    AND (CRTFCDOS.CER_RAM_CDGO = PLZAS.POL_RAM_CDGO)
    AND (CRTFCDOS.CER_CLSE_PLZA = PLZAS.POL_CDGO_CLSE)
    AND (CRTFCDOS.CER_NMRO_PLZA = PLZAS.POL_NMRO_PLZA)
    AND (ESTADO_CTA_RCBOS.EST_SLCTUD(+) = CRTFCDOS.CER_NMRO_CRTFCDO)
    AND (ESTADO_CTA_RCBOS.EST_PLZA(+) = CRTFCDOS.CER_NMRO_PLZA)
    AND (CRTFCDO_ANLDO.CER_NMRO_CRTFCDO(+) = CRTFCDOS.CER_NMRO_CRTFCDO)
    AND (CRTFCDO_ANLDO.CER_NMRO_PLZA(+) = CRTFCDOS.CER_NMRO_PLZA)
    AND (CRTFCDO_ANLDO.CER_CLSE_PLZA(+) = CRTFCDOS.CER_CLSE_PLZA)
    AND (CRTFCDO_ANLDO.CER_RAM_CDGO(+) = CRTFCDOS.CER_RAM_CDGO)
    AND (CG_REF_CODES.RV_LOW_VALUE = PLZAS.POL_ESTADO_PLZA))
GROUP BY PLZAS.POL_SUC_CIA_CDGO,
         SCRSL.SUC_CDGO,
         PLZAS.POL_NMRO_PLZA,
         PLZAS.POL_PRS_TPO_IDNTFCCION,
         PLZAS.POL_PRS_NMRO_IDNTFCCION,
         INITCAP(PK_TERCEROS.F_NOMBRES(PLZAS.POL_PRS_NMRO_IDNTFCCION,
                                       PLZAS.POL_PRS_TPO_IDNTFCCION)),
         PLZAS.POL_TPOPLZA,
         CRTFCDOS.CER_NMRO_CRTFCDO,
         CRTFCDOS.CER_CLSE_PLZA,
         CRTFCDOS.CER_RAM_CDGO,
         CRTFCDOS.CER_FCHA_DSDE_ACTUAL
HAVING    (SUM(NVL(CRTFCDOS.CER_GSTOS_EXPDCION, 0) +
               CRTFCDOS.CER_VLOR_IVA +
               CRTFCDOS.CER_VLOR_PRMA_NTA +
               CRTFCDOS.CER_VLOR_PPLRIA +
               NVL(CRTFCDOS.CER_VLOR_CTA_FAX, 0) +
               NVL(CRTFCDOS.CER_VLOR_CTA_PRMA, 0)) / COUNT(9)) -
          (SUM(DECODE(ESTADO_CTA_RCBOS.EST_CDGO_CNCPTO, 'PRM',
                      ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'GSE',
                      ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'IVA',
                      ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CPL',
                      ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CFI',
                      ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CFX',
                      ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 0))) > 0
ORDER BY SUCURSAL, POLIZA;

SELECT CER_NMRO_PLZA, MIN(CER_FCHA_PRDCCION) FECHA, min(CER_FCHA_DSDE_ACTUAL)
FROM CRTFCDOS, PLZAS
WHERE CER_VLOR_SLDO > 2
  AND CER_FCHA_PRDCCION >= to_date('01/01/1900', 'dd/mm/yyyy')
  AND CER_FCHA_PRDCCION <= to_date('30/04/2025', 'dd/mm/yyyy')
  AND POL_TPOPLZA = 'C'
  AND CER_ESTDO_PRDCCION NOT IN ('00','70','80', '50')
  AND CER_RAM_CDGO = POL_RAM_CDGO
  AND CER_CLSE_PLZA = POL_CDGO_CLSE
  AND CER_NMRO_PLZA = POL_NMRO_PLZA
  AND CER_FCHA_PRDCCION < to_date('30/04/2025', 'dd/mm/yyyy') - 75
  AND CRTFCDOS.CER_NMRO_PLZA = 1143
GROUP BY CER_NMRO_PLZA
UNION
SELECT CER_NMRO_PLZA, MIN(CER_FCHA_PRDCCION) FECHA, min(CER_FCHA_DSDE_ACTUAL)
FROM PLZAS,CRTFCDOS
WHERE CER_VLOR_SLDO > 2
  AND CER_FCHA_PRDCCION >= to_date('01/01/1900', 'dd/mm/yyyy')
  AND CER_FCHA_PRDCCION <= to_date('30/04/2025', 'dd/mm/yyyy')
  AND ((CER_NMRO_CRTFCDO, CER_NMRO_PLZA) IN
       (SELECT A.EST_SLCTUD, A.EST_PLZA
        FROM ESTADO_CTA_RCBOS A
        WHERE A.EST_ESTDO_RCBO = 'I'
          AND A.EST_ORGEN_RCDO = 'P'
          AND A.EST_FCHA_MRA IS NULL
          AND A.EST_FCHA_MVTO > to_date('30/04/2025', 'dd/mm/yyyy')))
  AND POL_TPOPLZA = 'C'
  AND CER_ESTDO_PRDCCION NOT IN ('00','70','80', '50')
  AND CER_RAM_CDGO = POL_RAM_CDGO
  AND CER_CLSE_PLZA = POL_CDGO_CLSE
  AND CER_NMRO_PLZA = POL_NMRO_PLZA
  AND 2025-08-17 < 2025-08-18
  AND CRTFCDOS.CER_NMRO_PLZA = 1143
GROUP BY CER_NMRO_PLZA
ORDER BY CER_NMRO_PLZA;

SELECT CER_NMRO_PLZA, CER_FCHA_PRDCCION FECHA, CER_FCHA_DSDE_ACTUAL, CER_NMRO_CRTFCDO
FROM CRTFCDOS, PLZAS
WHERE CER_VLOR_SLDO > 2
  AND CER_FCHA_PRDCCION >= to_date('01/01/1900', 'dd/mm/yyyy')
  AND CER_FCHA_PRDCCION <= to_date('30/04/2025', 'dd/mm/yyyy')
  AND POL_TPOPLZA = 'C'
  AND CER_ESTDO_PRDCCION NOT IN ('00','70','80')
  AND CER_RAM_CDGO = POL_RAM_CDGO
  AND CER_CLSE_PLZA = POL_CDGO_CLSE
  AND CER_NMRO_PLZA = POL_NMRO_PLZA
  AND CER_FCHA_PRDCCION to_date('30/04/2025', 'dd/mm/yyyy') - 75<
  AND CRTFCDOS.CER_NMRO_PLZA = 1143



select s.CER_VLOR_TTAL_CRTFCDO, s.CER_VLOR_SLDO, s.CER_ESTDO_PRDCCION, s.*
from CRTFCDOS s
where s.CER_NMRO_CRTFCDO in ('2146412', '1640836', '1639121');

select s.CER_VLOR_TTAL_CRTFCDO, s.CER_VLOR_SLDO, s.CER_ESTDO_PRDCCION, s.*
from CRTFCDOS s
where s.CER_NMRO_CRTFCDO in ('2022911','2149927','2152750','2158493');

select * from estado_cta_rcbos where est_slctud in (2030451);

SELECT PLZAS.POL_SUC_CIA_CDGO COD_CIA,
       SCRSL.SUC_CDGO SUCURSAL,
       PLZAS.POL_NMRO_PLZA Poliza,
       CRTFCDOS.CER_NMRO_CRTFCDO NumCert,
       CRTFCDOS.CER_FCHA_DSDE_ACTUAL FECHA_CER,
       (SUM(NVL(CRTFCDOS.CER_GSTOS_EXPDCION, 0) +
            CRTFCDOS.CER_VLOR_IVA +
            CRTFCDOS.CER_VLOR_PRMA_NTA +
            CRTFCDOS.CER_VLOR_PPLRIA +
            NVL(CRTFCDOS.CER_VLOR_CTA_FAX, 0) +
            NVL(CRTFCDOS.CER_VLOR_CTA_PRMA, 0)) / COUNT(9)) -
       (SUM(DECODE(ESTADO_CTA_RCBOS.EST_CDGO_CNCPTO, 'PRM',
                   ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'GSE',
                   ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'IVA',
                   ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CPL',
                   ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CFI',
                   ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 'CFX',
                   ESTADO_CTA_RCBOS.EST_VLOR_AFNZDO, 0))) AS DIFERENCIA
FROM PLZAS, CRTFCDOS, SCRSL, ESTADO_CTA_RCBOS, CRTFCDO_ANLDO
WHERE CRTFCDOS.CER_VLOR_SLDO > 2
  AND CRTFCDOS.CER_NMRO_PLZA = 10884
  AND CRTFCDOS.CER_ESTDO_PRDCCION NOT IN ('00', '70', '80', '50')
  AND ESTADO_CTA_RCBOS.EST_ESTDO_RCBO(+) = 'I'
  AND ESTADO_CTA_RCBOS.EST_ORGEN_RCDO(+) = 'P'
  AND ESTADO_CTA_RCBOS.EST_FCHA_MRA(+) IS NULL
  AND ESTADO_CTA_RCBOS.EST_FCHA_MVTO(+) BETWEEN to_date('01/01/1900', 'dd/mm/yyyy') AND (to_date('30/04/2025', 'dd/mm/yyyy') + 1)
  AND ((PLZAS.POL_SUC_CIA_CDGO = SCRSL.SUC_CIA_CDGO)
    AND (PLZAS.POL_SUC_CDGO = SCRSL.SUC_CDGO)
    AND (PLZAS.POL_TPOPLZA = 'C')
    AND (CRTFCDOS.CER_RAM_CDGO = PLZAS.POL_RAM_CDGO)
    AND (CRTFCDOS.CER_CLSE_PLZA = PLZAS.POL_CDGO_CLSE)
    AND (CRTFCDOS.CER_NMRO_PLZA = PLZAS.POL_NMRO_PLZA)
    AND (ESTADO_CTA_RCBOS.EST_SLCTUD(+) = CRTFCDOS.CER_NMRO_CRTFCDO)
    AND (ESTADO_CTA_RCBOS.EST_PLZA(+) = CRTFCDOS.CER_NMRO_PLZA)
    AND (CRTFCDO_ANLDO.CER_NMRO_CRTFCDO(+) = CRTFCDOS.CER_NMRO_CRTFCDO)
    AND (CRTFCDO_ANLDO.CER_NMRO_PLZA(+) = CRTFCDOS.CER_NMRO_PLZA)
    AND (CRTFCDO_ANLDO.CER_CLSE_PLZA(+) = CRTFCDOS.CER_CLSE_PLZA)
    AND (CRTFCDO_ANLDO.CER_RAM_CDGO(+) = CRTFCDOS.CER_RAM_CDGO))
GROUP BY PLZAS.POL_SUC_CIA_CDGO,
         SCRSL.SUC_CDGO,
         PLZAS.POL_NMRO_PLZA,
         CRTFCDOS.CER_NMRO_CRTFCDO,
         CRTFCDOS.CER_FCHA_DSDE_ACTUAL
ORDER BY DIFERENCIA DESC;

----ESTADOS DE CERTIFICADOS
select *
--DISTINCT RV_DOMAIN
from cg_ref_codes c
where rv_domain like '%ESTADO_PRODUCCION%';

select s.CER_VLOR_TTAL_CRTFCDO, s.CER_VLOR_SLDO, s.CER_ESTDO_PRDCCION, s.*
from CRTFCDOS s
where s.CER_NMRO_CRTFCDO in (
                             2030451,
                             2022828,
                             1687958,
                             2022911,
                             2005416,
                             2017216,
                             2012164,
                             2013012
    );

select s.CER_VLOR_TTAL_CRTFCDO, s.CER_VLOR_SLDO, s.CER_ESTDO_PRDCCION, s.CER_FCHA_PRDCCION, s.*
from CRTFCDOS s
where s.CER_NMRO_PLZA in (
                            748
    );

  ---CER_FCHA_PRDCCION <
 select to_date('01/11/2025', 'dd/mm/yyyy') - 75  from dual;

select s.CER_VLOR_TTAL_CRTFCDO, s.CER_VLOR_SLDO, s.CER_ESTDO_PRDCCION, s.CER_FCHA_PRDCCION, s.CER_FCHA_DSDE_ACTUAL FECHA_CER, s.*
from CRTFCDOS s
where s.CER_ESTDO_PRDCCION NOT IN ('00', '70', '80', '50')
  and CER_VLOR_SLDO > 2
  and s.CER_NMRO_PLZA = 1702;

select s.CER_VLOR_TTAL_CRTFCDO, s.CER_VLOR_SLDO, s.CER_ESTDO_PRDCCION, s.CER_FCHA_PRDCCION, s.CER_FCHA_DSDE_ACTUAL FECHA_CER, s.*
from CRTFCDOS s
where  CER_VLOR_SLDO > 2
  and s.CER_NMRO_PLZA = 1702;


----CER_ESTDO_PRDCCION: 00-SIN FACTURACION (NO SE A FACTURADO PRIMA AUN)| 20-PRIMA SIN PAGAR | 30-PRIMA PAGADA | 40-FACTURADO PARCIAL | 50-FACTURADO TOTAL | 60-ANULADO

SELECT *
FROM CG_REF_CODES
WHERE RV_DOMAIN like 'ESTADO_PRODUCCION';

SELECT * FROM PROCESOS_MENSUALES WHERE FECHA_CREACION >= to_date('01/09/2025', 'dd/mm/yyyy');

select count(*)
from PRVSION_PRMAS;

select *
from PRVSION_PRMAS
where PRO_NMRO_CRTFCDO = 2177655;

-----tablas donde debe aparecer la provision---------
select *
from PRVSION_PRMAS
where PRO_FCHA_CRCION > to_date('2025-07-01', 'YYYY-MM-DD');
select * from intrfaz_cntble where inc_dcmnto = '2177655';

SELECT
    PP.PRO_NMRO_CRTFCDO CERTIFICADO,
    PP.PRO_NMRO_PLZA POLIZA,
    PP.PRO_CLSE_PLZA CLASE,
    PP.PRO_RAM_CDGO RAMO,
    PP.PRO_FCHA_PRVSION FEC_PROVISION,
    PP.PRO_VLOR VALOR ,
    P.POL_PRS_TPO_IDNTFCCION TIP_IDE,
    P.POL_PRS_NMRO_IDNTFCCION IDE,
    UPPER(PK_TERCEROS.F_NOMBRES(P.POL_PRS_NMRO_IDNTFCCION, P.POL_PRS_TPO_IDNTFCCION)) NOMBRE
FROM PRVSION_PRMAS PP,
     PLZAS P
WHERE PP.PRO_NMRO_PLZA = P.POL_NMRO_PLZA
  AND  PRO_FCHA_CRCION  <= TO_DATE(SYSDATE, 'DD/MM/YYYY');

select * from PLZAS;

select TRUNC(SYSDATE) from dual;

SELECT /*+ LEADING(PP) USE_NL(P) INDEX(P POL_PK) */
    PP.PRO_NMRO_PLZA AS POLIZA,
    P.POL_PRS_NMRO_IDNTFCCION IDENTIFICACION,
    UPPER(PK_TERCEROS.F_NOMBRES(P.POL_PRS_NMRO_IDNTFCCION, P.POL_PRS_TPO_IDNTFCCION)) AS NOMBRE,
    PP.PRO_NMRO_CRTFCDO AS CERTIFICADO,
    FECHA_CER,
    PP.PRO_VLOR
FROM PRVSION_PRMAS PP
         INNER JOIN PLZAS P
                    ON PP.PRO_NMRO_PLZA = P.POL_NMRO_PLZA
                        AND PP.PRO_CLSE_PLZA = P.POL_CDGO_CLSE
                        AND PP.PRO_RAM_CDGO = P.POL_RAM_CDGO
WHERE PP.PRO_FCHA_CRCION <= TRUNC(SYSDATE);



SELECT /*+ LEADING(PP) USE_NL(P C) INDEX(P POL_PK) INDEX(C CER_PK) */
    PP.PRO_NMRO_PLZA                                                                  AS POLIZA,
    P.POL_PRS_NMRO_IDNTFCCION                                                         AS IDENTIFICACION,
    UPPER(PK_TERCEROS.F_NOMBRES(P.POL_PRS_NMRO_IDNTFCCION, P.POL_PRS_TPO_IDNTFCCION)) AS NOMBREPOLIZA,
    PP.PRO_NMRO_CRTFCDO                                                               AS NUMCERT,
    C.CER_FCHA_DSDE_ACTUAL                                                            AS FECHA_CER,
    PP.PRO_VLOR                                                                       AS PRIMA
FROM PRVSION_PRMAS PP
         INNER JOIN PLZAS P
                    ON PP.PRO_NMRO_PLZA = P.POL_NMRO_PLZA
                        AND PP.PRO_CLSE_PLZA = P.POL_CDGO_CLSE
                        AND PP.PRO_RAM_CDGO = P.POL_RAM_CDGO
         INNER JOIN CRTFCDOS C
                    ON PP.PRO_NMRO_CRTFCDO = C.CER_NMRO_CRTFCDO
                        AND PP.PRO_NMRO_PLZA = C.CER_NMRO_PLZA
                        AND PP.PRO_CLSE_PLZA = C.CER_CLSE_PLZA
                        AND PP.PRO_RAM_CDGO = C.CER_RAM_CDGO
WHERE PP.PRO_FCHA_CRCION <= TRUNC(SYSDATE);

SELECT /*+ LEADING(PP) USE_NL(P C) INDEX(P POL_PK) INDEX(C CER_PK) */
   COUNT(*)
FROM PRVSION_PRMAS PP
         INNER JOIN PLZAS P
                    ON PP.PRO_NMRO_PLZA = P.POL_NMRO_PLZA
                        AND PP.PRO_CLSE_PLZA = P.POL_CDGO_CLSE
                        AND PP.PRO_RAM_CDGO = P.POL_RAM_CDGO
         INNER JOIN CRTFCDOS C
                    ON PP.PRO_NMRO_CRTFCDO = C.CER_NMRO_CRTFCDO
                        AND PP.PRO_NMRO_PLZA = C.CER_NMRO_PLZA
                        AND PP.PRO_CLSE_PLZA = C.CER_CLSE_PLZA
                        AND PP.PRO_RAM_CDGO = C.CER_RAM_CDGO
WHERE PP.PRO_FCHA_CRCION <= TRUNC(SYSDATE);

SELECT * FROM PRVSION_PRMAS ORDER BY PRO_FCHA_CRCION DESC;